name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Lint, test, build and Docker
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 24
          package-manager-cache: false

      - name: Enable Corepack
        run: corepack enable

      - name: Prepare Yarn
        run: corepack prepare yarn@4.18.0 --activate

      - name: Check versions
        run: |
          node --version
          yarn --version

      - name: Install dependencies
        run: yarn install --immutable

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test

      - name: Build
        run: yarn build

      - name: Generate SBOM
        run: yarn sbom

      - name: Upload CycloneDX SBOM
        uses: actions/upload-artifact@v6
        with:
          name: cyclonedx-sbom
          path: sbom/bom.json
          if-no-files-found: error

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity=high --package-manager=yarn --file=yarn.lock

      - name: Build Docker image
        run: docker build -t devops-tasks-api:${{ github.sha }} .

  terraform:
    name: Terraform validate
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: infra

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: 1.10.5

      - name: Terraform fmt
        run: terraform fmt -check

      - name: Terraform init
        run: terraform init -input=false

      - name: Terraform validate
        run: terraform validate